language: java
sudo: false
jdk:
  - openjdk8
scala: 2.12.7
branches:
  only:
    - master
cache:
  directories:
  - "$HOME/.m2"
script:
  - cd docker/ops-playground-image/java/explore-flink/
  - mvn package
