language: java
sudo: false
jdk:
  - openjdk8
scala: 2.12.7
branches:
  only:
    - master
cache:
  directories:
  - "$HOME/.m2"
script:
  - cd docker/ops-playground-image/java/explore-flink/
  - mvn package
  - cd ../../../../

after_success:
  - cd operations-playground
  - docker-compose build -t felipeogutierrez/explore-flink:latest
  # Log in to the docker CLI. Log in to docker in a single command line
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push felipeogutierrez/explore-flink:latest
