language: java
sudo: false
jdk:
  - openjdk8
scala: 2.12.7
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
before_install:
  - git clone https://github.com/geotools/geotools.git
  - cd geotools && mvn install && cd ..
script:
  - mvn clean package

