apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: kafka
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  - name: prometheus-0
    port: 9250
  - name: prometheus-1
    port: 9251
  selector:
    app: flink
    component: jobmanager