apiVersion: v1
kind: Service
metadata:
  name: grafana-service-rest
spec:
  type: NodePort
  ports:
  - name: rest
    port: 3000
    targetPort: 3000
    nodePort: 30011
  selector:
    app: flink
    component: grafana