apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: 3
  serviceName: kafka
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: kafka # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: kafka # has to match .spec.selector.matchLabels
    spec:
      restartPolicy: Always
      containers:
      - name: kafka
        image: confluentinc/cp-enterprise-kafka:5.5.0
        imagePullPolicy: IfNotPresent # Always
        # command: ['sh', '-c', 'for i in 1 2 3; do echo "job-1 `date`" && sleep 5m; done;', 'ls']
        # lifecycle:
        #   postStart:
        #     exec:
              # command: ["sh", "-c", "sleep 2s && '[[ $(kafka-topics --zookeeper zookeeper:2181 --list)' =~ 'tpc-h-order' ]] || $(echo 'felipe-felipe-felipe-felipe-felipe-felipe-felipe-felipe-felipe-felipe-felipe')"]
              # command: ["sh", "-c", "sleep 2s && '[[ $(kafka-topics --zookeeper zookeeper:2181 --list)' =~ 'tpc-h-order' ]] || $(kafka-topics --create --topic tpc-h-order --partitions 3 --replication-factor 1 --zookeeper zookeeper:2181)"]
              # command: ['sh', '-c', 'sleep 1m && kafka-topics --create --topic tpc-h-order --partitions 3 --replication-factor 1 --zookeeper zookeeper:2181']
        ports:
        - containerPort: 9092
          name: kafka-0
        - containerPort: 9093
          name: kafka-1
        - containerPort: 9094
          name: kafka-2
        - containerPort: 7071
        env:
        - name: MY_METADATA_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: STAS_DELAY
          value: "120"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181 # zookeeper-2.zookeeper.default.svc.cluster.local
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INSIDE://$(MY_POD_IP):9092"
        - name: KAFKA_LISTENERS
          value: "INSIDE://$(MY_POD_IP):9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INSIDE"