apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer-tpch-order
  namespace: kafka
spec:
  template:
    metadata:
      labels:
        app: kafka-producer-tpch-order
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: tpch-dbgen-data
          persistentVolumeClaim:
            claimName: tpch-dbgen-data-pvc
        - name: tpch-dbgen-datarate
          persistentVolumeClaim:
            claimName: tpch-dbgen-datarate-pvc
      containers:
        - name: kafka-producer-tpch
          image: felipeogutierrez/explore-flink:1.11.2-scala_2.12
          imagePullPolicy: Always # Always/IfNotPresent
          volumeMounts:
            - mountPath: /opt/tpch-dbgen/data
              name: tpch-dbgen-data
              subPath: data
            - mountPath: /tmp
              name: tpch-dbgen-datarate
              subPath: tmp
          env:
          # command: ['sh', '-c', 'for i in 1 2 3; do echo "job-1 `date`" && sleep 5m; done;', 'ls']
          command: ["java"]
          args: ["-cp", "explore-flink.jar:/opt/flink/lib/*", "org.sense.flink.App", "-app", "41", "-bootstrap.servers", "10.111.85.76:9092", "-topic", "my-topic"]
          ports:
          - containerPort: 9092
          - containerPort: 9093
          - containerPort: 9094
