apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kafka
  labels:
    app: flink
data:
  prometheus.yml: |+
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 15s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'flink'
        scrape_interval: 15s
        static_configs:
          - targets: ['flink-jobmanager:9250', 'flink-jobmanager:9251', 'flink-taskmanager-0.flink-taskmanager.kafka.svc.cluster.local:9250', 'flink-taskmanager-1.flink-taskmanager.kafka.svc.cluster.local:9250', 'flink-taskmanager-2.flink-taskmanager.kafka.svc.cluster.local:9250']
        metrics_path: /
      - job_name: 'kafka'
        scrape_interval: 15s
        static_configs:
          - targets: ['172.18.0.21:9404', '172.18.0.22:9404', '172.18.0.15:9404']
        metrics_path: /
      - job_name: 'zookeeper'
        scrape_interval: 15s
        static_configs:
          - targets: ['172.18.0.5:9404', '172.18.0.13:9404', '172.18.0.7:9404']
        metrics_path: /
