apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-rest
  namespace: kafka
spec:
  type: NodePort
  ports:
  - name: rest
    port: 9090
    targetPort: 9090
    nodePort: 30091
  selector:
    app: flink
    component: prometheus