apiVersion: batch/v1
kind: Job
metadata:
  name: tpch-dbgen-job
  namespace: kafka
spec:
  template:
    metadata:
      labels:
        app: flink
        component: tpch-dbgen
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: tpch-dbgen-data
          persistentVolumeClaim:
            claimName: tpch-dbgen-data-pvc
        - name: tpch-dbgen-datarate
          persistentVolumeClaim:
            claimName: tpch-dbgen-datarate-pvc
      containers:
        - name: tpch-dbgen
          image: felipeogutierrez/tpch-dbgen:latest
          imagePullPolicy: IfNotPresent # Always/IfNotPresent
          volumeMounts:
          - mountPath: /opt/tpch-dbgen/data
            name: tpch-dbgen-data
            subPath: data
          - mountPath: /tmp
            name: tpch-dbgen-datarate
            subPath: tmp