apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpch-dbgen-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: tpch-dbgen
  template:
    metadata:
      labels:
        component: tpch-dbgen
    spec:
      containers:
      - name: tpch-dbgen
        image: felipeogutierrez/tpch-dbgen
        # imagePullPolicy: Always