name: Run Test Suites

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Check out your repository
      - name: Set up JDK 8
        working-directory: docker/ops-playground-image/java/explore-flink/
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: mvn cobertura:cobertura
      - run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov
      - uses: codecov/codecov-action@v1
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov # Upload to Codecov
